version: "3.9"

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache-spark-hadoop-cluster:3.5.8
    container_name: master
    hostname: master
    command: ["/usr/local/bin/start-master-node.sh"]
    ports:
      # Spark Master
      - "7077:7077"
      # Spark Master UI
      - "8080:8080"
      # Hadoop NameNode UI
      - "9870:9870"
      # Hadoop FS
      - "9000:9000"
      # Spark Application UI range
      - "4040-4060:4040-4060"
    volumes:
      - master_namenode:/data/hdfs/namenode
      - master_secondary:/data/hdfs/secondary

    networks:
      - spark-network

  slave01:
    image: apache-spark-hadoop-cluster:3.5.8
    container_name: slave01
    hostname: slave01
    command: ["/usr/local/bin/start-worker-node.sh"]
    depends_on:
      - master
    ports:
      # Worker UI
      - "8081:8081"
      # Spark UI range
      - "4061-4080:4040-4059"
    volumes:
      - slave01_datanode:/data/hdfs/datanode
    networks:
      - spark-network

  slave02:
    image: apache-spark-hadoop-cluster:3.5.8
    container_name: slave02
    hostname: slave02
    command: ["/usr/local/bin/start-worker-node.sh"]
    depends_on:
      - master
    ports:
      # Worker UI
      - "8082:8081"
      # Spark UI range
      - "4081-4100:4040-4059"
    volumes:
      - slave02_datanode:/data/hdfs/datanode
    networks:
      - spark-network

  submit:
    image: apache-spark-hadoop-cluster:3.5.8
    container_name: spark-submit-job
    hostname: submit
    profiles: ["job"]
    command:
      - /usr/local/spark/bin/spark-submit
      - --master
      - spark://master:7077
      - --deploy-mode
      - client
      - --conf
      - spark.ui.enabled=true
      - --conf
      - spark.ui.port=4040
      - /opt/workspace/verify_spark.py
    depends_on:
      - master
      - slave01
      - slave02
    ports:
      # Spark Application UI
      - "4101-4120:4040-4059"
    networks:
      - spark-network

  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    container_name: pyspark-notebook
    hostname: notebook
    user: "0:0"
    depends_on:
      - master
      - slave01
      - slave02
    ports:
      # Jupyter
      - "8888:8888"
      # Spark Application UI range
      - "4121-4140:4040-4059"
    environment:
      - SPARK_MASTER=spark://master:7077
    volumes:
      - ./notebooks:/opt/workspace/notebooks
      - ./data:/opt/workspace/data

    networks:
      - spark-network

volumes:
  master_namenode:
  master_secondary:
  slave01_datanode:
  slave02_datanode:

networks:
  spark-network:
    driver: bridge